language: node_js
dist: bionic
sudo: required
services:
  - xvfb
node_js:
  - 'stable'
before_install:
  - stty cols 80
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
      - fluxbox
cache:
  directories:
    - node_modules
before_script:
  - sudo apt install xsel
  - 'export DISPLAY=:99.0'
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - yarn global add serve
script: yarn run build && yarn run test-headless
